### ISSUE TITLE
Incompatibility with Bulma framework

### ISSUE THREAD

**Issue by tompec** [metafizzy/huebee#15]
Hi David,

I'm trying to use Huebee with the CSS framework [Bulma](https://bulma.io/).

But for some reason, the canvas doesn't show up:
![image](https://user-images.githubusercontent.com/17140634/33794098-8364e0ba-dcf7-11e7-9c19-38d54dffbff6.png)

Here's the codepen: https://codepen.io/tompec/pen/jagwYe

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like Bulma has a `.is-hidden` style:

``` css
.is-hidden {
  display: none!important;
}
```

Which is causing the issue. You can override it by adding this  CSS:

``` css
.huebee.is-hidden,
.huebee__cursor.is-hidden {
  display: block !important;
}
```

See demo https://codepen.io/desandro/pen/d3b654dc0a58e69c148bcdc31e6d4043/

---

**Add a 👍  reaction** to this issue if you would like to see this issue resolved within Huebee. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).
